<a href="https://colab.research.google.com/github/BoyoungH/2D-to-3D-Nerf/blob/main/image_processing_for_colmap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

focal_length 뽑아오기

In [ ]:
def replace_in_file(file_path, old_str, new_str):
    # 파일 읽어들이기
    fr = open(file_path, 'r')
    lines = fr.readlines()
    fr.close()

    # old_str -> new_str 치환
    fw = open(file_path, 'w')
    for line in lines:
        fw.write(line.replace(old_str, new_str))
    fw.close()

In [ ]:
with open('/content/scan8/cameras.txt', 'r') as f:
    camera_data = f.readlines()

print(camera_data[1])

#   CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]



In [ ]:
camera_column_name = camera_data[1].strip().split(',')
#column_name[4] = 'PARAMS[focal_length]'
print(camera_column_name)

['#   CAMERA_ID', ' MODEL', ' WIDTH', ' HEIGHT', ' PARAMS[]']


In [ ]:
camera_data_split = [x.strip().split() for x in camera_data[3:]]
refine_camera_data = []
for i in range(len(camera_data_split)):
  refine_camera_data.append(camera_data_split[i][:5])
print(refine_camera_data)

[['1', 'SIMPLE_RADIAL', '400', '300', '745.28961636126962']]


In [ ]:
camera_df = pd.DataFrame(refine_camera_data, columns = camera_column_name)

camera_df

#   CAMERA_ID          MODEL  WIDTH  HEIGHT            PARAMS[]
0             1  SIMPLE_RADIAL    400     300  745.28961636126962

-> cameras.txt에 있는 focal length 값 뽑아오기 가능 !

qw,qx,qy,qz,tx,ty,tz 뽑아오기

In [ ]:
replace_in_file('/content/scan8/images.txt', '#', '')

In [ ]:
with open('/content/scan8/images.txt', 'r') as f:
    images_data = f.readlines()

print(images_data[1])

   IMAGE_ID, QW, QX, QY, QZ, TX, TY, TZ, CAMERA_ID, NAME



In [ ]:
images_column_name = images_data[1].strip().split(', ')
print(images_column_name)

['IMAGE_ID', 'QW', 'QX', 'QY', 'QZ', 'TX', 'TY', 'TZ', 'CAMERA_ID', 'NAME']


In [ ]:
images_data_split = [x.strip().split() for x in images_data[4:]]
refine_images_data = []
#data의 개수 = 70 = (camera_data-1) * 2
#image data가 들어있는 행: 4 - 68 까지 2의 배수
for i in range(len(images_data_split)):
  if i %2 == 0:
    refine_images_data.append(images_data_split[i])
print(refine_images_data)


[['1', '0.97522620979056496', '0.14243964564697434', '-0.087819624328406232', '-0.14468068519436561', '3.7481555347002478', '1.1463303856982512', '2.0975119934115765', '1', '000000.png'], ['2', '0.98040634386071512', '0.17678096679692704', '0.055832632658654187', '0.066592851165968261', '1.6107348967776218', '2.7974755317012541', '1.6533587577594184', '1', '000001.png'], ['3', '0.92103032814896069', '0.19796349912259059', '0.1955759915689686', '0.2725135210714737', '-1.0661375626719864', '3.2948725419342266', '1.8143376733913039', '1', '000002.png'], ['4', '0.80098169649894346', '0.20551282016160591', '0.32151063252659851', '0.46132820832379678', '-3.5786834249375183', '2.5323592332690703', '2.526773334299059', '1', '000003.png'], ['8', '0.85365798383417235', '0.11665604770678173', '0.32642093060342076', '0.38872713982124513', '-2.9317415227300336', '1.7142163312048722', '1.8136412865180229', '1', '000007.png'], ['9', '0.93188462851897091', '0.10226474045885457', '0.22466857154745054',

In [ ]:
images_df = pd.DataFrame(refine_images_data, columns = images_column_name)
images_df

IMAGE_ID                   QW                     QX  \
0         1  0.97522620979056496    0.14243964564697434   
1         2  0.98040634386071512    0.17678096679692704   
2         3  0.92103032814896069    0.19796349912259059   
3         4  0.80098169649894346    0.20551282016160591   
4         8  0.85365798383417235    0.11665604770678173   
5         9  0.93188462851897091    0.10226474045885457   
6        10  0.98026081422742239   0.085271870413848205   
7        11  0.99771637903763999   0.067315838843398978   
8        12   0.9880031065149103  -0.048841166401904154   
9        13  0.99936747215161736  -0.034467958783984037   
10       14   0.9911882354522753  -0.019317749347027496   
11       15  0.96384128739587083  -0.003216116846777751   
12       16   0.9191240198251911  0.0098313972573218535   
13       17  0.85223187930157929   0.026610844971349676   
14       18   0.7704938950346788   0.040911687566292175   
15       22  0.78083477737704921  -0.046887285236302964   
16       23  0.85011985071127982  -0.067099670090302155   
17       24  0.90185578052537352  -0.078849310134874284   
18       25  0.94578196321764352  -0.096402737887933077   
19       26  0.97461221337653126   -0.11047173989596332   
20       27  0.98922894676616924   -0.12309371954574715   
21       28  0.99027338039367974   -0.13209870042792454   
22       29  0.96244353783786118   -0.23655778421706489   
23       30  0.97233959482734933    -0.2308630428868528   
24       31  0.97080309503927509   -0.22301598355306049   
25       32  0.95822779111813439    -0.2117693932313916   
26       33  0.93520116347965121   -0.19798390069936758   
27       34  0.89938275430411019   -0.18086228872261803   
28       35  0.85572280021696445   -0.16009719335904896   
29       36  0.80367097013281086   -0.14630569241202276   
30       42  0.78459415360503937   -0.22811845809376688   
31       43  0.83103063620521123   -0.25538752267945791   
32       44   0.8742233957690061   -0.27234792416678055   
33       45  0.90398660255706997   -0.28850643638112017   
34       46  0.92658503238601919   -0.30664374677463491   
35       47  0.94213088356164953    -0.3130961114932978   
36       48  0.94494021752596102   -0.32499668496894013   
37       49  0.93878639104591277   -0.32970596109138695   

                        QY                     QZ                    TX  \
0    -0.087819624328406232   -0.14468068519436561    3.7481555347002478   
1     0.055832632658654187   0.066592851165968261    1.6107348967776218   
2       0.1955759915689686     0.2725135210714737   -1.0661375626719864   
3      0.32151063252659851    0.46132820832379678   -3.5786834249375183   
4      0.32642093060342076    0.38872713982124513   -2.9317415227300336   
5      0.22466857154745054     0.2658138351323549   -1.1408495770096194   
6      0.11598946844532979    0.13551342153485982   0.72663287273193744   
7    0.0054659426902584967  0.0008534115868915487    2.4370147059598635   
8     -0.10782979369815215  -0.099182345064040445     3.720234868646771   
9   -0.0085359456023501867  -0.001937280368379829     2.609379374215556   
10    0.090588755085571307   0.094690991721581977    1.2787594716316526   
11     0.18655836718654215    0.19025142558254238  -0.16401671645412561   
12     0.27731701083589239    0.27965989220729526   -1.5933639557567396   
13     0.37149288734352998    0.36740403030611474   -3.0435679690175661   
14     0.45338434112372145    0.44621522918718998   -4.2127355017799966   
15     0.48129601079659379    0.39554112670238051    -4.007561829226252   
16     0.40139834820807296    0.33417546252864633   -2.9487554314635931   
17     0.32471551783382085    0.27385903290221658   -1.8802255639746093   
18     0.23428832891951021    0.20325346027065336   -0.5768884523101121   
19     0.14311503678196752    0.13207995483249363   0.69054028776985965   
20    0.051760920259212202   0.059956936397784044    1.8964437863781269   
21    -0.04120499768722178  -0.014515977215611098  

->위의 정제된 데이터에서 qw,qx,qy,qz,tx,ty,tx 만 따로 빼오기

In [ ]:
import numpy as np

In [ ]:
num = len(camera_data_split)
print(num)

1


In [ ]:
final_images_data = images_df.loc[:,['QW','QX','QY','QZ','TX','TY','TZ']]
numpy_images_data = images_df[['QW','QX','QY','QZ','TX','TY','TZ']].values.tolist()
numpy_images_data[32]

['0.8742233957690061',
 '-0.27234792416678055',
 '0.34064498776725438',
 '0.2133566375841178',
 '-1.4075739637143927',
 '-3.1170536573619345',
 '1.8589091288673778']

In [ ]:
# 카메라 pose 값을 나타내는 변수
qw=[]
qx=[]
qy=[]
qz=[]
tx=[]
ty=[]
tz=[]
for i in range(num):
    qw.append(numpy_images_data[i][0])
    qx.append(numpy_images_data[i][1])
    qy.append(numpy_images_data[i][2])
    qz.append(numpy_images_data[i][3])
    tx.append(numpy_images_data[i][4])
    ty.append(numpy_images_data[i][5])
    tz.append(numpy_images_data[i][6])


In [ ]:
tx = [float (i) for i in tx]
ty = [float (i) for i in ty]
tz = [float (i) for i in tz]

In [ ]:
qw=list(map(float, qw))
qx=list(map(float, qx))
qy=list(map(float, qy))
qz=list(map(float, qz))
tx=list(map(float, tx))
ty=list(map(float, ty))
tz=list(map(float, tz))

print(type(qw[0]))

<class 'float'>


In [ ]:
# 회전 쿼터니언으로부터 회전 행렬을 구함
R = []
for i in range(num):
  R.append(np.array([[1-2*qy[i]**2-2*qz[i]**2, 2*qx[i]*qy[i]-2*qz[i]*qw[i], 2*qx[i]*qz[i]+2*qy[i]*qw[i]],
                [2*qx[i]*qy[i]+2*qz[i]*qw[i], 1-2*qx[i]**2-2*qz[i]**2, 2*qy[i]*qz[i]-2*qx[i]*qw[i]],
                [2*qx[i]*qz[i]-2*qy[i]*qw[i], 2*qy[i]*qz[i]+2*qx[i]*qw[i], 1-2*qx[i]**2-2*qy[i]**2]]))

In [ ]:
# 변환 행렬을 구함
T = []
P = []
for i in range(num):
  T.append(np.array([tx[i], ty[i], tz[i]]).reshape(-1, 1))
for i in range(num):
  P.append(np.hstack([R[i], T[i]]))
for i in range(num):
  P[i] = np.vstack([P[i], [0.0, 0.0, 0.0, 1.0]])


In [ ]:
print(P[0])

[[ 0.94271043  0.2571748  -0.21250453  3.74815553]
 [-0.30721078  0.91755689 -0.25241014  1.14633039]
 [ 0.13007147  0.30323336  0.94399732  2.09751199]
 [ 0.          0.          0.          1.        ]]


R,G,B 값 추출

In [ ]:
with open('/content/scan8/points3D.txt', 'r') as f:
    rgb_data = f.readlines()

print(rgb_data[1])

#   POINT3D_ID, X, Y, Z, R, G, B, ERROR, TRACK[] as (IMAGE_ID, POINT2D_IDX)



In [ ]:
replace_in_file('/content/scan8/points3D.txt','#', '')

In [ ]:
rgb_column_name = rgb_data[1].strip().split(', ')
print(rgb_column_name)

['#   POINT3D_ID', 'X', 'Y', 'Z', 'R', 'G', 'B', 'ERROR', 'TRACK[] as (IMAGE_ID', 'POINT2D_IDX)']


In [ ]:
rgb_data[2]

'# Number of points: 986, mean track length: 6.4046653144016226\n'

In [ ]:
print(len(rgb_data))

989


In [ ]:
rgb_data_split = [x.strip().split() for x in rgb_data[3:]]
refine_rgb_data = []
for i in range(len(rgb_data_split)):
  refine_rgb_data.append(rgb_data_split[i][:10])
print(refine_rgb_data)


[['944', '-2.4784399852660415', '-1.2438287623511233', '5.5720957926206989', '220', '137', '126', '0.21404251676513608', '33', '151'], ['1', '-3.709602478019705', '-1.7825296953780931', '5.8544452822212945', '242', '86', '73', '0.054041864982732508', '13', '1'], ['1054', '-3.0476066036894536', '-0.80486636927439292', '5.2384186741518652', '247', '160', '148', '0.23146004782814719', '16', '211'], ['393', '-3.5738050158744397', '0.21668001047282442', '5.4060389569421172', '119', '72', '64', '0.093567804031078824', '12', '236'], ['2', '-3.6248927309207271', '-1.7094187865679131', '5.7559932665387201', '226', '77', '64', '0.27029091397521549', '13', '6'], ['3', '-3.6777897303644753', '-1.5119090629719625', '5.5883287124798482', '240', '105', '94', '0.14921141849668187', '13', '7'], ['1064', '-1.8711707694884205', '-0.48853833070335978', '5.9986575383518126', '120', '54', '47', '0.13746237721754229', '45', '61'], ['387', '-2.7149356406386675', '-0.32471871185982065', '5.3028865272054713', '

In [ ]:
rgb_df = pd.DataFrame(refine_rgb_data, columns = rgb_column_name)
rgb_df

#   POINT3D_ID                    X                     Y  \
0              944  -2.4784399852660415   -1.2438287623511233   
1                1   -3.709602478019705   -1.7825296953780931   
2             1054  -3.0476066036894536  -0.80486636927439292   
3              393  -3.5738050158744397   0.21668001047282442   
4                2  -3.6248927309207271   -1.7094187865679131   
..             ...                  ...                   ...   
981           1149  -3.4207928010361992   -1.2376711050338076   
982           1151  -2.5377328928911447    1.6665622026345381   
983           1152  -2.5911893445144267    1.6331689240758844   
984           1160  -2.5889960801454754    1.5470241510664449   
985           1164  -2.1072341926665579   -1.3438561546344285   

                      Z    R    G    B                 ERROR  \
0    5.5720957926206989  220  137  126   0.21404251676513608   
1    5.8544452822212945  242   86   73  0.054041864982732508   
2    5.2384186741518652  247  160  148   0.23146004782814719   
3    5.4060389569421172  119   72   64  0.093567804031078824   
4    5.7559932665387201  226   77   64   0.27029091397521549   
..                  ...  ...  ...  ...                   ...   
981  5.3641857656447884  175   83   75  0.080589575361806137   
982  7.0043961445864413  255  255  250   0.17250581083366248   
983  7.0478100379305157  241  218  205   0.05687269610382413   
984   7.107414723672882  182  163  153   0.10486193059290147   
985  6.3876948519773578   88   27   22     1.356812215039376   

    TRACK[] as (IMAGE_ID POINT2D_IDX)  
0                     33          151  
1                     13            1  
2                     16          211  
3                     12          236  
4                     13            6  
..                   ...          ...  
981                    8            5  
982                    3          211  
983                    3          262  
984                    3          274  
985                   17          331  

[986 rows x 10 columns]

->위의 정제된 데이터에서 R,G,B값만 뺴오기

In [ ]:
final_rgb_data = rgb_df.loc[:,['R','G','B']]
numpy_rgb_data = rgb_df[['R','G','B']].values.tolist()
numpy_rgb_data

[['220', '137', '126'],
 ['242', '86', '73'],
 ['247', '160', '148'],
 ['119', '72', '64'],
 ['226', '77', '64'],
 ['240', '105', '94'],
 ['120', '54', '47'],
 ['237', '150', '139'],
 ['254', '246', '245'],
 ['93', '67', '62'],
 ['254', '246', '245'],
 ['156', '121', '109'],
 ['139', '82', '74'],
 ['192', '78', '69'],
 ['242', '97', '84'],
 ['248', '205', '198'],
 ['169', '74', '66'],
 ['250', '137', '129'],
 ['115', '85', '77'],
 ['241', '142', '138'],
 ['117', '79', '67'],
 ['183', '112', '106'],
 ['250', '176', '165'],
 ['247', '152', '140'],
 ['180', '120', '112'],
 ['131', '86', '78'],
 ['165', '100', '96'],
 ['192', '69', '56'],
 ['168', '144', '135'],
 ['140', '92', '82'],
 ['247', '143', '134'],
 ['249', '211', '197'],
 ['156', '74', '66'],
 ['251', '240', '233'],
 ['222', '117', '105'],
 ['204', '90', '79'],
 ['251', '148', '132'],
 ['90', '45', '40'],
 ['208', '96', '86'],
 ['196', '70', '59'],
 ['149', '63', '56'],
 ['134', '90', '81'],
 ['100', '56', '50'],
 ['155', '67', '

In [ ]:
# RGB값을 나타내는 변수
r = []
g = []
b = []
for i in range(len(numpy_rgb_data)):
    r.append(numpy_rgb_data[i][0])
    g.append(numpy_rgb_data[i][1])
    b.append(numpy_rgb_data[i][2])
r = [int (i) for i in r]
g = [int (i) for i in g]
b = [int (i) for i in b]
print(numpy_rgb_data)


new_list = []
for inner_list in numpy_rgb_data:
    temp_list = []
    for element in inner_list:
        temp_list.append(int(element))
    new_list.append(temp_list)

numpy_rgb_data_int=new_list
print(numpy_rgb_data_int[1][2])

print(np.array(numpy_rgb_data_int[1]).ndim)
#print(numpy_rgb_data.shape)
#print(type(numpy_rgb_data[0][1]))
#print(print(numpy_rgb_data[i][j]))
#print(numpy_rgb_data)
numpy_rgb_data_int=[]
#for i in range(len(numpy_rgb_data)):
##    numpy_rgb_data_int=list(map(int, numpy_rgb_data[i]))
#    print(numpy_rgb_data[i][j])

#list_a = [int (i) for i in list_a]


#print(numpy_rgb_data_int)





[['220', '137', '126'], ['242', '86', '73'], ['247', '160', '148'], ['119', '72', '64'], ['226', '77', '64'], ['240', '105', '94'], ['120', '54', '47'], ['237', '150', '139'], ['254', '246', '245'], ['93', '67', '62'], ['254', '246', '245'], ['156', '121', '109'], ['139', '82', '74'], ['192', '78', '69'], ['242', '97', '84'], ['248', '205', '198'], ['169', '74', '66'], ['250', '137', '129'], ['115', '85', '77'], ['241', '142', '138'], ['117', '79', '67'], ['183', '112', '106'], ['250', '176', '165'], ['247', '152', '140'], ['180', '120', '112'], ['131', '86', '78'], ['165', '100', '96'], ['192', '69', '56'], ['168', '144', '135'], ['140', '92', '82'], ['247', '143', '134'], ['249', '211', '197'], ['156', '74', '66'], ['251', '240', '233'], ['222', '117', '105'], ['204', '90', '79'], ['251', '148', '132'], ['90', '45', '40'], ['208', '96', '86'], ['196', '70', '59'], ['149', '63', '56'], ['134', '90', '81'], ['100', '56', '50'], ['155', '67', '60'], ['250', '192', '180'], ['255', '255',

In [ ]:
from numpy import load

data = load('/content/tiny_nerf_data.npz')

lst = data.files
images=data['images']
#for item in lst:
#    print(item)
#    print(data[item])
print(images.shape)
print(images[1][50][50])
#print(data['poses'])

(106, 100, 100, 3)
[0.43333337 0.3648897  0.09430147]


In [ ]:
import cv2
import os

imgrgb=[]
image_array=[]
# 이미지가 저장된 경로
image_dir = '/content/scan1'

# 이미지 파일 리스트 가져오기
image_files = os.listdir(image_dir)

# 이미지 파일마다 RGB 값 추출
for file in image_files:
    # 이미지 로드
    image_path = os.path.join(image_dir, file)
    image = cv2.imread(image_path)

    # 이미지를 numpy 배열로 변환
    image_array[file] = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    for i in range(image_array[file].shape[0]):
      for j in range(image_array[file].shape[1]):
        # (i, j) 위치의 픽셀 값 (RGB)
          imgrgb[file] = image_array[file][i, j]

print(imgrgb[1])

TypeError: ignored

In [ ]:
from PIL import Image
import os

# 이미지 파일들이 들어 있는 폴더 경로
folder_path = '/content/scan1'

# 모든 이미지에서 추출한 RGB 값 저장할 리스트
imgrgb = []

# 폴더 내 모든 이미지 파일에 대해 반복문 실행
for filename in os.listdir(folder_path):
    if filename.endswith('.jpg') or filename.endswith('.png'):
        # 이미지 파일 열기
        image_path = os.path.join(folder_path, filename)
        image = Image.open(image_path)

        # 이미지 RGB 값 추출
        rgb_values = list(image.getdata())

        # 추출한 RGB 값을 imgrgb 배열에 추가
        imgrgb.extend(rgb_values)

print(f"Total RGB values: {len(imgrgb)}")
print(imgrgb[0])

Total RGB values: 5880000
(15, 16, 16)
